name: AutoHexoGenerate # 部署

on: # 触发条件
  push:
    branches:
      - dev # 推送到 master 分支

  release:
    types:
      - published # 推送新版本号

  workflow_dispatch: # 手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
#      - uses: actions/checkout@v2
#      - name: Setup tmate session
#        uses: mxschmitt/action-tmate@v3

      - name: Checkout # Checkout 仓库
        uses: actions/checkout@v2
        with:
          ref: dev

      - name: Setup Node # 安装 Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "20.x"

      - name: Install Hexo # 安装 Hexo
        run: |
          npm install -g hexo-cli
          npm install

      - name: Generate # 生成
        run: |
          hexo clean
          hexo generate
      - name: Deploy # 部署
        run: |
          git config --global user.name "shenbing"
          git config --global user.email "shenbinglife@163.com"
          export TZ='Asia/Shanghai'
          cd public/
          git init -b main
          git add -A
          git commit -m "Create by workflows"
          git remote add origin https://github.com/shenbinglife/shenbinglife.github.io.git
          git push https://shenbinglife:${{ secrets.AUTO_HEXO_GENERATE_GITHUB_TOKEN }}@github.com/shenbinglife/shenbinglife.github.io.git -f